export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';

export const FETCH_CAR_INFO_REQUEST = 'FETCH_CAR_INFO_REQUEST';
export const FETCH_CAR_INFO_SUCCESS = 'FETCH_CAR_INFO_SUCCESS';
export const FETCH_CAR_INFO_FAILURE = 'FETCH_CAR_INFO_FAILURE';

export const ADD_CAR_SUCCESS = 'ADD_CAR_SUCCESS';
export const ADD_CAR_FAILURE = 'ADD_CAR_FAILURE';

export const REMOVE_CAR_SUCCESS = 'REMOVE_CAR_SUCCESS';
export const REMOVE_CAR_FAILURE = 'REMOVE_CAR_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY_FAILURE = 'REMOVE_CATEGORY_FAILURE';

export const FETCH_MANUFACTURERS_REQUEST = 'FETCH_MANUFACTURERS_REQUEST';
export const FETCH_MANUFACTURERS_SUCCESS = 'FETCH_MANUFACTURERS_SUCCESS';
export const FETCH_MANUFACTURERS_FAILURE = 'FETCH_MANUFACTURERS_FAILURE';

export const ADD_MANUFACTURER_SUCCESS = 'ADD_MANUFACTURER_SUCCESS';
export const ADD_MANUFACTURER_FAILURE = 'ADD_MANUFACTURER_FAILURE';

export const REMOVE_MANUFACTURER_SUCCESS = 'REMOVE_MANUFACTURER_SUCCESS';
export const REMOVE_MANUFACTURER_FAILURE = 'REMOVE_MANUFACTURER_FAILURE';

export const LOGIN_STATUS_REQUEST = 'LOGIN_STATUS_REQUEST';
export const LOGIN_STATUS_SUCCESS = 'LOGIN_STATUS_SUCCESS';
export const NOT_LOGGEDIN = 'NOT_LOGGEDIN';
export const API_ERRORS = 'API_ERRORS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const FETCH_BOOKINGS_REQUEST = 'FETCH_BOOKINGS_REQUEST';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE';

export const BOOK_CAR_SUCCESS = 'BOOK_CAR_SUCCESS';
export const BOOK_CAR_FAILURE = 'BOOK_CAR_FAILURE';

export const BASE_URL = 'https://car-booking-api-app.herokuapp.com';
// https://car-booking-api-app.herokuapp.com
// http://localhost:3000
