export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';

export const FETCH_CAR_INFO_REQUEST = 'FETCH_CAR_INFO_REQUEST';
export const FETCH_CAR_INFO_SUCCESS = 'FETCH_CAR_INFO_SUCCESS';
export const FETCH_CAR_INFO_FAILURE = 'FETCH_CAR_INFO_FAILURE';

export const ADD_CAR_SUCCESS = 'ADD_CAR_SUCCESS';
export const ADD_CAR_FAILURE = 'ADD_CAR_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const FETCH_MANUFACTURERS_REQUEST = 'FETCH_MANUFACTURERS_REQUEST';
export const FETCH_MANUFACTURERS_SUCCESS = 'FETCH_MANUFACTURERS_SUCCESS';
export const FETCH_MANUFACTURERS_FAILURE = 'FETCH_MANUFACTURERS_FAILURE';

export const ADD_MANUFACTURER_SUCCESS = 'ADD_MANUFACTURER_SUCCESS';
export const ADD_MANUFACTURER_FAILURE = 'ADD_MANUFACTURER_FAILURE';

export const LOGIN_STATUS = 'LOGIN_STATUS';
export const API_ERRORS = 'API_ERRORS';
